plugins:
  -  rubocop-rails
  -  rubocop-capybara
  -  rubocop-rspec
  -  rubocop-performance

AllCops:
    NewCops: enable
    SuggestExtensions: false

Style/Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
    Max: 160

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/ClassLength:
  Max: 160

Rails/ReversibleMigration:
  Enabled: false